### ISSUE TITLE
Future development

### ISSUE THREAD

**Issue by jharej** [roelmann/moodle-theme_handlebar#12]
Hi,

is there a plan for future development of this theme? 

Thanks for answer.
bye

**Comment by roelmann** [comment]
Updating to 3.6 - yes: was due to have been done this weekend, but unfortunately 'life' got in the way :) Hope to have a 3.6 version released early this week
Ongoing maintenance - yes: the theme will be supported as long as it is practical to do so
New features - unlikely, but depends on the feature requested (and/or development support - code or financial): more likely new features would go into another new theme in the series - I have a couple which are all work in progress but none are close to release due to work commitments etc.

**Comment by jharej** [comment]
Hi, we are prepared to finance the upgrade of this theme to 3.6 and the realisation of issue #10. What is the next step? 
bye

**Comment by roelmann** [comment]
Hi,
I don't believe there is very much work involved in upgrading the theme to 3.6, or in addressing issue #10 I would probably be able to do both for around £250, although the timescale would need to be towards the end of March as I am currently engaged in some marking, alongside my full-time job, so wouldn't be able to address this until that is completed.

**Comment by jharej** [comment]
I've written to you on LinkedIn regarding financing the upgrade of
handlebar theme. Still waiting for your reply. Our Moodle users are
frustrated as they are unable to unenroll themselves from courses... If you
didn't get the message, please write to me on janko.harej@tscng.org and
send data for the contract.
thanks and bye
Janko Harej

V V pon., 4. mar. 2019 ob 13:13 je oseba Richard Oelmann <
notifications@github.com> napisala:

**Comment by roelmann** [comment]
Apologies, I very rarely use LinkedIn for anything, it is far more useful to contact me via moodle.org forums or DM https://moodle.org/user/profile.php?id=480148

However, I am somewhat confused having looked at this as there is already a 3.6 version on the Moodle plugin database, which has the course admin link on the student panel.

I do need to update the plugin entry to point at gitlab, rather than here on github for the latest updates, an oversight on my part.
So if you are using the plugins database to download the theme, simply upgrade from there - 
Or if you are using git to manage your plugins, simply point to https://gitlab.com/ro-mdl-theme_handlebar and you should be able to update anyway with no need to pay for the work as it had already been done.

I will correct the VCS link on the database as soon as I get chance.

**Comment by jharej** [comment]
Thanks - issue solved

bye
Janko

V V sre., 10. apr. 2019 ob 09:32 je oseba Richard Oelmann <
notifications@github.com> napisala:

**Comment by jharej** [comment]
Thanks.
