### ISSUE TITLE
Processing of strings

### ISSUE THREAD

**Issue by jharej** [roelmann/moodle-theme_handlebar#6]
Hi,

I've allready created an issue regarding "dynamic links". I now open a new one because I have a propossal. I've tested the plugin https://moodle.org/plugins/filter_filtercodes - that enables users to enter codes (courseid, userid ...) that transforms into real data when viewed from students - with your theme. I found out that it does not work. I've created an issue on https://github.com/michael-milette/moodle-filter_filtercodes/issues/7 and got an response, that the theme probably doesn't use format_string() or format_text() functions as you can read on a link above. Can you look at this issue and do anything about it?

I realy miss some links in your theme that are essential for our work and would like to add them.

thanks and bye
Janko

**Comment by roelmann** [comment]
Hi Janko,
Thanks for this. I will look at it as soon as I get chance, but it may be next week or the week after at the earliest as I am really very busy in work right now (beginning of a new semester), so unpaid community work has to be delayed for a short time.
Richard

**Comment by roelmann** [comment]
Janko,
Please can you let me know where you are trying to use these codes and where this format_string or format_text is needed.
You say in your comments to Michael that it works in labels, so where doesn't it work please?

**Comment by jharej** [comment]
Hi,
I've attached na image where you can see it. It's in the section /admin/settings.php?section=themesettinghandlebar#theme_handlebar_links / Links Popup Pages, where I would like to add some links for the teachers - I would like the link to also have an id of current course.

![izbor_036](https://user-images.githubusercontent.com/10975112/30802226-13bff0fc-a1e6-11e7-9967-27021cc6eaa9.jpg)

bye

**Comment by roelmann** [comment]
Hmmm,
that is an actual URL link though and I'm not sure formatting that as plain text or html is a good idea. Strikes me that doing that could open up a lot of potential security holes.
As it is, the settings are passed through a function that, where relevant parses them as format_text with FORMAT_PLAIN or FORMAT_HTML as sent to the function, but otherwise as format_string.
I don't currently have the filtercodes plugin installed - I'm currently rebuilding my dev server.
In the meantime, you could try making the change below to https://github.com/roelmann/moodle-theme_handlebar/blob/master/classes/output/core_renderer.php#L434 and https://github.com/roelmann/moodle-theme_handlebar/blob/master/classes/output/core_renderer.php#L488

`                            'url' => theme_handlebar_get_setting('stafflink' . $i . 'url','format_html'),`
and
`                            'url' => theme_handlebar_get_setting('studentlink' . $i . 'url','format_html'),`

Can you tell me if such a link works on say the Social Media url settings in other themes eg Essential? If so I will investigate how it is done there.

**Comment by roelmann** [comment]
Hmmm (2)
Also, on my localhost development, I had already changed the settings that supply this value to PARAM_URL to ensure cleaner input and ensure a genuine url is added - this setting rejects the {courseid} filter, so if you update in the future, you will need to remove that security feature.

**Comment by roelmann** [comment]
OK - solution would be
As above core_renderer.php L434 and L488 (at the time of writing) add ,'format_html'
Also linkspage_settings.php (per github currently, not yet in plugins released version) L87 remove PARAM_URL
As the PARAM_URL would prevent the url using this filter anyway, and I feel that this is the correct code for a setting as a url, I do not propose to make this change in the community released version.
